import 'package:dto/dto.dart';
import 'package:dto/model/message.dart';
import 'package:firebase_auth/firebase_auth.dart' hide User;
import 'package:flutter/material.dart';
import 'package:scroll_and_cook/screens/messagerie_screen.dart';
import 'package:scroll_and_cook/screens/profil_screen.dart';
import 'package:scroll_and_cook/styles/colors.dart';
import 'package:scroll_and_cook/styles/padding.dart';
import 'package:scroll_and_cook/styles/radius.dart';
import 'package:scroll_and_cook/styles/size.dart';
import 'package:scroll_and_cook/styles/spacings.dart';
import 'package:scroll_and_cook/styles/texts.dart';
import 'package:scroll_and_cook/widgets/custom_image.dart';

class VerticalItemListView extends StatelessWidget {
  const VerticalItemListView({
    super.key,
    required String path,
    required String username,
    required String id,
    required int isMessagerie,

    String? idRecipe,
    String? imageRecipe,
    String? ownerRecipe,
    String? titleRecipe,
    String? ownerRecipeImage
  }) : _path = path, _username = username, _id = id, _isMessagerie = isMessagerie
  , _idRecipe = idRecipe, _imageRecipe = imageRecipe, _ownerRecipe = ownerRecipe, _titleRecipe = titleRecipe, _ownerRecipeImage = ownerRecipeImage;

  final String _path;
  final String _username;
  final String _id;
  final int _isMessagerie;

  final String? _idRecipe;
  final String? _imageRecipe;
  final String? _ownerRecipe;
  final String? _titleRecipe;
  final String? _ownerRecipeImage;


  @override
  Widget build(BuildContext context) {
    final currentUser = FirebaseAuth.instance.currentUser?.uid;

    final db = FirestoreODM(
      appSchema
    );
    return Padding(
      padding: EdgeInsets.all(kHorizontalPadding),
      child: InkWell(
        onTap: () async {
          // 1 = Profil
          if(_isMessagerie == 1)
            Navigator.push(
          context,
          MaterialPageRoute<void>(
            builder: (context) =>
              ProfilScreen(
                isPersonalProfile: false,
                idUtilisateur: _id,
              )
            )
          );
          // 2 = Messagerie
          if(_isMessagerie == 2){
            Navigator.push(context,
              MaterialPageRoute<void>(
              builder: (context) =>
                MessagerieScreen(
                  idFriend: _id,
                )
              )
            );
          }
          // 3 = Création Message
          if(_isMessagerie == 3){
            Message message = Message(
              id: FirestoreODM.autoGeneratedId,
              text: "Dite bonjour a votre ami",
              isSentByMe: true,
              createdAt: DateTime.now(),
              type: "text",
            );
            await db.users(currentUser!).friends(_id).messages.insert(message);

            final friend = await db.users(currentUser).friends(_id).get();

            await db.users(currentUser).friends(_id).update(friend!.copyWith(hasMessage: true));

            Navigator.pop(context);
          }
          // 4 = Envoyer à un amis
          if(_isMessagerie == 4){
            Message messageTrue = Message(
              id: FirestoreODM.autoGeneratedId,
              type: "recipe",
              recipeId: _idRecipe,
              recipeImage: _imageRecipe,
              recipeOwnerId: _ownerRecipe,
              recipeTitle: _titleRecipe,
              recipeOwnerImage: _ownerRecipeImage,
              isSentByMe: true,
              createdAt: DateTime.now(),
            );

            Message messageFalse = Message(
              id: FirestoreODM.autoGeneratedId,
              type: "recipe",
              recipeId: _idRecipe,
              recipeImage: _imageRecipe,
              recipeOwnerId: _ownerRecipe,
              recipeTitle: _titleRecipe,
              recipeOwnerImage: _ownerRecipeImage,
              isSentByMe: true,
              createdAt: DateTime.now(),
            );
            await db.users(currentUser!).friends(_id).messages.insert(messageTrue);

            await db.users(_id).friends(currentUser!).messages.insert(messageFalse);

            Navigator.pop(context);
          }
        },
        child: Container(
          height: kHeightVerticalItemListView,
          width: MediaQuery.of(context).size.width * 0.8,
          decoration: BoxDecoration(
              color: kSecondColor,
              borderRadius: kNormalRadius
          ),
          child: Row(
            children: [
              Padding(
                padding: EdgeInsets.only(left: kPaddingVerticalItemListView),
                child: CustomImage(size: kSizeFriendPDP, path: _path, assetOrNot: false, ),
              ),
              Expanded(
                child: Center(
                  child: Text(
                    _username,
                    style: kTextFriendResult,
                  ),
                )
              ),
            ],
          ),
        ),
      ),
    );
  }
}
